In [1]:
import numpy as np

In [2]:
l =[2,3,4,5]

In [3]:
ar = np.array(l)

In [4]:
ar

array([2, 3, 4, 5])

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar2 = np.array([[2,3,4,5],[3,4,6,7]])

In [7]:
ar2

array([[2, 3, 4, 5],
       [3, 4, 6, 7]])

In [8]:
type(ar2)

numpy.ndarray

In [9]:
np.asarray(l)    # give it same as make array

array([2, 3, 4, 5])

In [10]:
np.asanyarray(l)         # give it same as make array

array([2, 3, 4, 5])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[2, 3, 4, 5]])

In [13]:
ar

array([2, 3, 4, 5])

In [14]:
c = ar

In [15]:
c

array([2, 3, 4, 5])

In [16]:
c[1] = 100

In [17]:
c

array([  2, 100,   4,   5])

In [18]:
ar

array([  2, 100,   4,   5])

In [19]:
p = np.copy(ar)

In [20]:
p

array([  2, 100,   4,   5])

In [21]:
ar

array([  2, 100,   4,   5])

In [22]:
p[0] = 300

In [23]:
p

array([300, 100,   4,   5])

In [24]:
ar

array([  2, 100,   4,   5])

In [25]:
np.fromfunction(lambda i,j : i== j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j: i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [27]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
d = (i for i in range(5))

In [29]:
d

<generator object <genexpr> at 0x000001ECAF060660>

In [30]:
np.fromiter(d,dtype=float)

array([0., 1., 2., 3., 4.])

In [31]:
np.fromstring('44 66 878',sep=(' '))

array([ 44.,  66., 878.])

In [32]:
ar = np.array([1,2,3,4])

In [33]:
ar

array([1, 2, 3, 4])

In [34]:
ar.ndim

1

In [35]:
ar2 = np.array([[1,2,3,4]])

In [36]:
ar2

array([[1, 2, 3, 4]])

In [37]:
ar2.ndim

2

In [38]:
ar

array([1, 2, 3, 4])

In [39]:
ar.size

4

In [40]:
ar2

array([[1, 2, 3, 4]])

In [41]:
ar2.size

4

In [42]:
ar

array([1, 2, 3, 4])

In [43]:
ar.shape

(4,)

In [44]:
ar2.shape

(1, 4)

In [45]:
a_r = np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [46]:
a_r

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [47]:
a_r.size

10

In [48]:
a_r.shape

(2, 5)

In [49]:
a_r.ndim

2

In [50]:
ar.dtype

dtype('int32')

In [51]:
ar2.dtype

dtype('int32')

In [52]:
a_r.dtype

dtype('int32')

In [53]:
arr = np.array([['a','b',2,4],['c',4,5,6]])

In [54]:
arr

array([['a', 'b', '2', '4'],
       ['c', '4', '5', '6']], dtype='<U11')

In [55]:
arr.dtype

dtype('<U11')

In [56]:
arr2= np.array([(2.3,4.5,5),(4,6,7)])

In [57]:
arr2

array([[2.3, 4.5, 5. ],
       [4. , 6. , 7. ]])

In [58]:
arr2.dtype

dtype('float64')

In [59]:
np.arange(1.5,5.5)

array([1.5, 2.5, 3.5, 4.5])

In [60]:
np.arange(1.5,5.5,0.5)

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [61]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [66]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
on = np.ones((4,4,5))

In [68]:
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [69]:
on+3

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [70]:
on*5

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [71]:
np.empty((8))

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [72]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [75]:
np.linspace(2.5,5,20)

array([2.5       , 2.63157895, 2.76315789, 2.89473684, 3.02631579,
       3.15789474, 3.28947368, 3.42105263, 3.55263158, 3.68421053,
       3.81578947, 3.94736842, 4.07894737, 4.21052632, 4.34210526,
       4.47368421, 4.60526316, 4.73684211, 4.86842105, 5.        ])

In [76]:
np.logspace(2.5,5,20,base=2)

array([ 5.65685425,  6.19703857,  6.78880617,  7.43708284,  8.14726475,
        8.92526334,  9.77755458, 10.71123281, 11.73406984, 12.85457963,
       14.08208913, 15.42681597, 16.89995346, 18.5137638 , 20.28168011,
       22.21841828, 24.34009946, 26.6643842 , 29.21061955, 32.        ])

In [77]:
np.random.rand(3,4)

array([[0.18369467, 0.58962336, 0.39552622, 0.69791506],
       [0.07163854, 0.82964429, 0.17219339, 0.38913021],
       [0.58971388, 0.53029803, 0.65267194, 0.88969376]])

In [78]:
np.random.randn(3,4)

array([[-0.53146405, -0.13672909,  1.38976404, -1.48205194],
       [-1.1899458 , -0.27762004,  1.24933411,  2.07840051],
       [-1.20489856,  0.16541747, -1.62006587, -0.30285534]])

In [79]:
random_numbers = np.random.randint(2,10,(4,4))

In [80]:
import pandas as pd

In [81]:
col =['A','B','C','D']

In [82]:
pd.DataFrame(data=random_numbers,columns=col)

A  B  C  D
0  6  7  8  6
1  2  5  5  8
2  4  9  6  6
3  9  7  9  9

In [83]:
df = pd.DataFrame(np.random.randint(1,20,(200,300)))

In [84]:
df.head()

0    1    2    3    4    5    6    7    8    9    ...  290  291  292  293  \
0   14   14    1    4    2    1   16   16   10   11  ...    4   14   10    1   
1    5    3   16    4    6   19   11   13   13    7  ...   12    5    2    2   
2    4    8   14    1   11   11   17   12    9   15  ...   19    3   12   12   
3   17   12    4    7    3    8    4    4    4   10  ...   17   13   10    8   
4   16   14   11   10   10    2   19   19   18   19  ...    3    9   19   14   

   294  295  296  297  298  299  
0    8   10   18   10    2   11  
1   11    3   12   16   12   16  
2   17    8    8    2    8    2  
3    4    8    3   17   10    7  
4    9   15   18   12    2   13  

[5 rows x 300 columns]

In [85]:
df.to_csv('test.csv')

In [86]:
ar = np.random.rand(3,4)

In [87]:
ar

array([[0.25677925, 0.42244982, 0.1664372 , 0.96265305],
       [0.07503239, 0.31396901, 0.19852165, 0.37563473],
       [0.17827672, 0.95306077, 0.92955565, 0.22958576]])

In [88]:
ar.reshape(6,2)

array([[0.25677925, 0.42244982],
       [0.1664372 , 0.96265305],
       [0.07503239, 0.31396901],
       [0.19852165, 0.37563473],
       [0.17827672, 0.95306077],
       [0.92955565, 0.22958576]])

In [89]:
ar.size

12

In [90]:
ar

array([[0.25677925, 0.42244982, 0.1664372 , 0.96265305],
       [0.07503239, 0.31396901, 0.19852165, 0.37563473],
       [0.17827672, 0.95306077, 0.92955565, 0.22958576]])

In [91]:
ar[1][1]

0.3139690116519882

In [92]:
ar[2:5,1]

array([0.95306077])

In [93]:
arr1 = np.random.randint(1,100,(5,5))

In [94]:
arr1

array([[29, 63, 90, 41, 16],
       [32, 63, 30,  5, 14],
       [84, 19,  6,  5, 15],
       [73, 90, 58, 61, 94],
       [17, 33, 14,  6, 67]])

In [95]:
arr1 > 50

array([[False,  True,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False,  True]])

In [96]:
arr1[arr1 > 50]

array([63, 90, 63, 84, 73, 90, 58, 61, 94, 67])

In [97]:
arr1

array([[29, 63, 90, 41, 16],
       [32, 63, 30,  5, 14],
       [84, 19,  6,  5, 15],
       [73, 90, 58, 61, 94],
       [17, 33, 14,  6, 67]])

In [98]:
arr1[1:4,1:3]

array([[63, 30],
       [19,  6],
       [90, 58]])

In [99]:
arr1[0][0]

29

In [100]:
arr1[0][0] = 5000

In [101]:
arr1

array([[5000,   63,   90,   41,   16],
       [  32,   63,   30,    5,   14],
       [  84,   19,    6,    5,   15],
       [  73,   90,   58,   61,   94],
       [  17,   33,   14,    6,   67]])

In [102]:
ar1 = np.random.randint(2,10,(4,4))

ar2 = np.random.randint(2,10,(4,4))

In [103]:
ar1

array([[3, 7, 8, 7],
       [6, 7, 3, 9],
       [5, 6, 5, 2],
       [8, 2, 7, 2]])

In [104]:
ar2

array([[7, 3, 4, 3],
       [6, 6, 6, 4],
       [9, 8, 4, 6],
       [6, 2, 6, 4]])

In [105]:
ar1 +ar2

array([[10, 10, 12, 10],
       [12, 13,  9, 13],
       [14, 14,  9,  8],
       [14,  4, 13,  6]])

In [106]:
ar1-ar2

array([[-4,  4,  4,  4],
       [ 0,  1, -3,  5],
       [-4, -2,  1, -4],
       [ 2,  0,  1, -2]])

In [107]:
ar1*ar2

array([[21, 21, 32, 21],
       [36, 42, 18, 36],
       [45, 48, 20, 12],
       [48,  4, 42,  8]])

In [108]:
ar1 @ ar2

array([[177, 129, 128, 113],
       [165, 102, 132, 100],
       [128,  95,  88,  77],
       [143,  96,  84,  82]])

In [109]:
ar1/0

C:\Users\Let\AppData\Local\Temp\ipykernel_1084\3042774750.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [110]:
ar1+100

array([[103, 107, 108, 107],
       [106, 107, 103, 109],
       [105, 106, 105, 102],
       [108, 102, 107, 102]])

In [111]:
ar1-100

array([[-97, -93, -92, -93],
       [-94, -93, -97, -91],
       [-95, -94, -95, -98],
       [-92, -98, -93, -98]])

In [112]:
ar1**2

array([[ 9, 49, 64, 49],
       [36, 49,  9, 81],
       [25, 36, 25,  4],
       [64,  4, 49,  4]])

In [113]:
ar1

array([[3, 7, 8, 7],
       [6, 7, 3, 9],
       [5, 6, 5, 2],
       [8, 2, 7, 2]])

In [114]:
row = np.zeros([4,4])

In [115]:
row

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
a = np.array([1,2,3,4])

In [117]:
a

array([1, 2, 3, 4])

In [118]:
row+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [119]:
b = np.array([[1,2,3,4]])

In [120]:
b

array([[1, 2, 3, 4]])

In [121]:
b_column = b.T

In [122]:
b_column

array([[1],
       [2],
       [3],
       [4]])

In [123]:
b_column+ row

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [124]:
ar = np.random.randint(1,4,(4,4))

In [125]:
ar

array([[3, 3, 1, 3],
       [2, 3, 2, 3],
       [3, 1, 3, 1],
       [3, 3, 2, 1]])

In [126]:
np.sqrt(ar)

array([[1.73205081, 1.73205081, 1.        , 1.73205081],
       [1.41421356, 1.73205081, 1.41421356, 1.73205081],
       [1.73205081, 1.        , 1.73205081, 1.        ],
       [1.73205081, 1.73205081, 1.41421356, 1.        ]])

In [127]:
np.exp(ar)

array([[20.08553692, 20.08553692,  2.71828183, 20.08553692],
       [ 7.3890561 , 20.08553692,  7.3890561 , 20.08553692],
       [20.08553692,  2.71828183, 20.08553692,  2.71828183],
       [20.08553692, 20.08553692,  7.3890561 ,  2.71828183]])

In [128]:
np.log2(ar)

array([[1.5849625, 1.5849625, 0.       , 1.5849625],
       [1.       , 1.5849625, 1.       , 1.5849625],
       [1.5849625, 0.       , 1.5849625, 0.       ],
       [1.5849625, 1.5849625, 1.       , 0.       ]])

In [129]:
np.log10(ar)

array([[0.47712125, 0.47712125, 0.        , 0.47712125],
       [0.30103   , 0.47712125, 0.30103   , 0.47712125],
       [0.47712125, 0.        , 0.47712125, 0.        ],
       [0.47712125, 0.47712125, 0.30103   , 0.        ]])

In [130]:
import numpy as np

In [131]:
ar = np.random.randint(1,10,(3,4))

In [132]:
ar

array([[9, 4, 9, 6],
       [2, 4, 6, 3],
       [9, 8, 5, 7]])

In [133]:
ar.shape

(3, 4)

In [134]:
ar.size

12

In [135]:
ar.reshape(6,2)

array([[9, 4],
       [9, 6],
       [2, 4],
       [6, 3],
       [9, 8],
       [5, 7]])

In [136]:
ar

array([[9, 4, 9, 6],
       [2, 4, 6, 3],
       [9, 8, 5, 7]])

In [137]:
ar.T

array([[9, 2, 9],
       [4, 4, 8],
       [9, 6, 5],
       [6, 3, 7]])

In [138]:
one_d = ar.flatten()

In [139]:
ar.ndim

2

In [140]:
one_d.shape

(12,)

In [141]:
one_d.ndim

1

In [142]:
one_d

array([9, 4, 9, 6, 2, 4, 6, 3, 9, 8, 5, 7])

In [143]:
np.expand_dims(one_d,axis=1)

array([[9],
       [4],
       [9],
       [6],
       [2],
       [4],
       [6],
       [3],
       [9],
       [8],
       [5],
       [7]])

In [144]:
np.expand_dims(one_d,axis=0)

array([[9, 4, 9, 6, 2, 4, 6, 3, 9, 8, 5, 7]])

In [145]:
a = np.array([[1],[2],[3],[4]])

In [146]:
a

array([[1],
       [2],
       [3],
       [4]])

In [147]:
ar1 = np.squeeze(a)

In [148]:
ar1

array([1, 2, 3, 4])

In [149]:
ar1.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [150]:
np.roll(ar1,2)

array([3, 4, 1, 2])

In [151]:
np.diag(ar1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [152]:
arr1 = np.random.randint(1,5,(3,3))

In [153]:
arr2 = np.random.randint(1,5,(3,3))

In [154]:
arr1

array([[3, 1, 3],
       [1, 3, 2],
       [1, 3, 2]])

In [155]:
arr2

array([[1, 4, 1],
       [4, 1, 3],
       [2, 3, 1]])

In [156]:
arr1+arr2

array([[4, 5, 4],
       [5, 4, 5],
       [3, 6, 3]])

In [157]:
arr1-arr2

array([[ 2, -3,  2],
       [-3,  2, -1],
       [-1,  0,  1]])

In [158]:
arr1*arr2

array([[3, 4, 3],
       [4, 3, 6],
       [2, 9, 2]])

In [159]:
arr1@arr2

array([[13, 22,  9],
       [17, 13, 12],
       [17, 13, 12]])

In [160]:
arr1 ** arr2

array([[ 3,  1,  3],
       [ 1,  3,  8],
       [ 1, 27,  2]])

In [161]:
arr1 /arr2

array([[3.        , 0.25      , 3.        ],
       [0.25      , 3.        , 0.66666667],
       [0.5       , 1.        , 2.        ]])

In [162]:
arr1 % arr2

array([[0, 1, 0],
       [1, 0, 2],
       [1, 0, 0]])

In [163]:
arr1 & arr2

array([[1, 0, 1],
       [0, 1, 2],
       [0, 3, 0]])

In [164]:
arr1

array([[3, 1, 3],
       [1, 3, 2],
       [1, 3, 2]])

In [165]:
arr2

array([[1, 4, 1],
       [4, 1, 3],
       [2, 3, 1]])

In [166]:
arr1 | arr2

array([[3, 5, 3],
       [5, 3, 3],
       [3, 3, 3]])

In [167]:
~arr1 

array([[-4, -2, -4],
       [-2, -4, -3],
       [-2, -4, -3]])

In [168]:
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False],
       [False, False,  True]])

In [169]:
r = np.array(['sudh','krish'])

In [170]:
r

array(['sudh', 'krish'], dtype='<U5')

In [171]:
np.char.capitalize(r)

array(['Sudh', 'Krish'], dtype='<U5')

In [172]:
np.char.title(r)

array(['Sudh', 'Krish'], dtype='<U5')

In [173]:
np.char.upper(r)

array(['SUDH', 'KRISH'], dtype='<U5')

In [174]:
np.char.lower(r)

array(['sudh', 'krish'], dtype='<U5')

In [175]:
arr1

array([[3, 1, 3],
       [1, 3, 2],
       [1, 3, 2]])

In [176]:
np.sin(arr1)

array([[0.14112001, 0.84147098, 0.14112001],
       [0.84147098, 0.14112001, 0.90929743],
       [0.84147098, 0.14112001, 0.90929743]])

In [177]:
np.cos(arr1)

array([[-0.9899925 ,  0.54030231, -0.9899925 ],
       [ 0.54030231, -0.9899925 , -0.41614684],
       [ 0.54030231, -0.9899925 , -0.41614684]])

In [178]:
np.tan(arr1)

array([[-0.14254654,  1.55740772, -0.14254654],
       [ 1.55740772, -0.14254654, -2.18503986],
       [ 1.55740772, -0.14254654, -2.18503986]])

In [179]:
np.tanh(arr1)

array([[0.99505475, 0.76159416, 0.99505475],
       [0.76159416, 0.99505475, 0.96402758],
       [0.76159416, 0.99505475, 0.96402758]])

In [180]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.47712125],
       [0.        , 0.47712125, 0.30103   ],
       [0.        , 0.47712125, 0.30103   ]])

In [181]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.73205081],
       [1.        , 1.73205081, 1.41421356],
       [1.        , 1.73205081, 1.41421356]])

In [182]:
np.power(arr1,2)

array([[9, 1, 9],
       [1, 9, 4],
       [1, 9, 4]], dtype=int32)

In [183]:
np.exp(arr1)

array([[20.08553692,  2.71828183, 20.08553692],
       [ 2.71828183, 20.08553692,  7.3890561 ],
       [ 2.71828183, 20.08553692,  7.3890561 ]])

In [184]:
np.mean(arr1)

2.111111111111111

In [185]:
np.median(arr1)

2.0

In [186]:
np.std(arr1)

0.8748897637790901

In [187]:
np.var(arr1)

0.7654320987654322

In [188]:
np.max(arr1)

3

In [189]:
np.min(arr1)

1

In [190]:
arr = np.array([2,3,4,5,6,7,6,665,3,434,6,4,55])

In [191]:
arr

array([  2,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [192]:
np.sort(arr)

array([  2,   3,   3,   4,   4,   5,   6,   6,   6,   7,  55, 434, 665])

In [193]:
np.searchsorted(arr,36)

12

In [194]:
arr1 = np.array([0,0,1,2,3,0,0,0,0,0,0,])

In [195]:
arr1

array([0, 0, 1, 2, 3, 0, 0, 0, 0, 0, 0])

In [196]:
np.count_nonzero(arr1)

3

In [197]:
np.where(arr > 10)

(array([ 7,  9, 12], dtype=int64),)

In [198]:
arr

array([  2,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [199]:
np.extract(arr > 10,arr)

array([665, 434,  55])

In [200]:
arr

array([  2,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [201]:
arr.byteswap()

array([   33554432,    50331648,    67108864,    83886080,   100663296,
         117440512,   100663296, -1727922176,    50331648, -1308557312,
         100663296,    67108864,   922746880])

In [202]:
arr

array([  2,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [203]:
b = arr

In [204]:
b

array([  2,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [205]:
b[0] = 200

In [206]:
b

array([200,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [207]:
arr

array([200,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [208]:
co_py = np.copy(arr)

In [209]:
co_py

array([200,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [210]:
arr

array([200,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [211]:
arr[0] = 1000

In [212]:
arr

array([1000,    3,    4,    5,    6,    7,    6,  665,    3,  434,    6,
          4,   55])

In [213]:
co_py

array([200,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [214]:
shallow_copy = arr.view()

In [215]:
shallow_copy


array([1000,    3,    4,    5,    6,    7,    6,  665,    3,  434,    6,
          4,   55])

In [216]:
arr

array([1000,    3,    4,    5,    6,    7,    6,  665,    3,  434,    6,
          4,   55])

In [217]:
arr[0] = 500

In [218]:
arr

array([500,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [219]:
shallow_copy

array([500,   3,   4,   5,   6,   7,   6, 665,   3, 434,   6,   4,  55])

In [220]:
import numpy.matlib as nm

In [221]:
nm.zeros([4,4])

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [222]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [223]:
nm.ones((4,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

#### write a code to print the data types of both the variables.

In [224]:
#       ***Given***


list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)

In [225]:
list_

[1, 2, 3, 4, 5]

In [226]:
for i in array_list:
    print("Type Of Array and Data Type of Array_list : ",type(i))

Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>


In [227]:
for i in list_:
    print("Type Of Array and Data Type of list_ : ",type(i))

Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>


In [228]:
array_list

array([1, 2, 3, 4, 5])

In [229]:
type(list_)

list

In [230]:
type(array_list)

numpy.ndarray

In [231]:
array_list.dtype

dtype('int32')

#### Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

array_list

In [232]:
type(array_list)

numpy.ndarray

In [233]:
type(list_)

list

In [234]:
for i in array_list:
    print("Type Of Array and Data Type of Array_list : ",type(i))

Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>
Type Of Array and Data Type of Array_list :  <class 'numpy.int32'>


In [235]:
for i in list_:
    print("Type Of Array and Data Type of list_ : ",type(i))

Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>
Type Of Array and Data Type of list_ :  <class 'int'>


#### Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [236]:
import numpy as np


num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [237]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [238]:
num_array.shape

(2, 3)

In [239]:
num_array.size

6

#### Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [240]:
z = np.zeros((3,3))

In [241]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [242]:
z.shape

(3, 3)

In [243]:
z.size

9

#### Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [244]:
e = np.eye(5)

In [245]:
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [246]:
e.shape

(5, 5)

In [247]:
e.size

25